# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7a35tcpg236-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/zhehengt/Desktop/Digital_Design_Lab/Chapter_3/conditional statement/conditional statement.cache/wt} [current_project]
set_property parent.project_path {C:/Users/zhehengt/Desktop/Digital_Design_Lab/Chapter_3/conditional statement/conditional statement.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {{C:/Users/zhehengt/Desktop/Digital_Design_Lab/Chapter_3/conditional statement/conditional statement.srcs/sources_1/new/prio_encoder_casez.v}}
catch { write_hwdef -file prio_encoder_casez.hwdef }
synth_design -top prio_encoder_casez -part xc7a35tcpg236-1
write_checkpoint -noxdef prio_encoder_casez.dcp
catch { report_utilization -file prio_encoder_casez_utilization_synth.rpt -pb prio_encoder_casez_utilization_synth.pb }
