# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7a35tcpg236-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/Github/xupsh/Digital_Design_lab/Chapter_10/OLED/OLED.cache/wt [current_project]
set_property parent.project_path E:/Github/xupsh/Digital_Design_lab/Chapter_10/OLED/OLED.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  E:/Github/xupsh/Digital_Design_lab/Chapter_10/OLED/OLED.srcs/sources_1/new/oled_clear.v
  E:/Github/xupsh/Digital_Design_lab/Chapter_10/OLED/OLED.srcs/sources_1/new/oled_write_data.v
  E:/Github/xupsh/Digital_Design_lab/Chapter_10/OLED/OLED.srcs/sources_1/new/spi_master.v
  E:/Github/xupsh/Digital_Design_lab/Chapter_10/OLED/OLED.srcs/sources_1/new/oled.v
  E:/Github/xupsh/Digital_Design_lab/Chapter_10/OLED/OLED.srcs/sources_1/new/oled_top.v
}
read_xdc E:/Github/xupsh/Digital_Design_lab/Chapter_10/OLED/OLED.srcs/constrs_1/new/PIN.xdc
set_property used_in_implementation false [get_files E:/Github/xupsh/Digital_Design_lab/Chapter_10/OLED/OLED.srcs/constrs_1/new/PIN.xdc]

catch { write_hwdef -file oled_top.hwdef }
synth_design -top oled_top -part xc7a35tcpg236-1
write_checkpoint -noxdef oled_top.dcp
catch { report_utilization -file oled_top_utilization_synth.rpt -pb oled_top_utilization_synth.pb }
