set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN P17 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports rxd]
set_property PACKAGE_PIN N5 [get_ports rxd]
set_property PACKAGE_PIN T4 [get_ports txd]
set_property IOSTANDARD LVCMOS33 [get_ports txd]
