# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7a35tcpg236-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/zhehengt/Desktop/Digital_Design_Lab/Chapter_5/FSM/FSM.cache/wt [current_project]
set_property parent.project_path C:/Users/zhehengt/Desktop/Digital_Design_Lab/Chapter_5/FSM/FSM.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib C:/Users/zhehengt/Desktop/Digital_Design_Lab/Chapter_5/FSM/FSM.srcs/sources_1/new/fsm_eg_2_seg.v
catch { write_hwdef -file fsm_eg_2_seg.hwdef }
synth_design -top fsm_eg_2_seg -part xc7a35tcpg236-1
write_checkpoint -noxdef fsm_eg_2_seg.dcp
catch { report_utilization -file fsm_eg_2_seg_utilization_synth.rpt -pb fsm_eg_2_seg_utilization_synth.pb }
