# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7a35tcpg236-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/zhehengt/Desktop/Digital_Design_Lab/Chapter_10/OLED_new/OLED_new.cache/wt [current_project]
set_property parent.project_path C:/Users/zhehengt/Desktop/Digital_Design_Lab/Chapter_10/OLED_new/OLED_new.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/zhehengt/Desktop/Digital_Design_Lab/Chapter_10/OLED_new/OLED_new.srcs/sources_1/imports/src/oled.v
  C:/Users/zhehengt/Desktop/Digital_Design_Lab/Chapter_10/OLED_new/OLED_new.srcs/sources_1/imports/src/oled_clear.v
  C:/Users/zhehengt/Desktop/Digital_Design_Lab/Chapter_10/OLED_new/OLED_new.srcs/sources_1/imports/src/spi_master.v
  C:/Users/zhehengt/Desktop/Digital_Design_Lab/Chapter_10/OLED_new/OLED_new.srcs/sources_1/imports/src/oled_write_data.v
  C:/Users/zhehengt/Desktop/Digital_Design_Lab/Chapter_10/OLED_new/OLED_new.srcs/sources_1/imports/src/oled_top.v
}
read_xdc C:/Users/zhehengt/Desktop/Digital_Design_Lab/Chapter_10/OLED_new/OLED_new.srcs/constrs_1/imports/src/PIN.xdc
set_property used_in_implementation false [get_files C:/Users/zhehengt/Desktop/Digital_Design_Lab/Chapter_10/OLED_new/OLED_new.srcs/constrs_1/imports/src/PIN.xdc]

catch { write_hwdef -file oled_top.hwdef }
synth_design -top oled_top -part xc7a35tcpg236-1
write_checkpoint -noxdef oled_top.dcp
catch { report_utilization -file oled_top_utilization_synth.rpt -pb oled_top_utilization_synth.pb }
